version: '2.2'

services:
## 基础镜像
  tools:
    build: ./tools
    image: yangzhenwei/centos7-tools
  jdk:
    build: ./jdk
    image: yangzhenwei/centos7-jdk
    depends_on:
      - tools
  maven:
    build: ./maven
    image: yangzhenwei/centos7-maven
    volumes:
      - mvn_repository:/root/.m2
    depends_on:
      - jdk
  nexus:
    build: ./nexus
    image: yangzhenwei/centos7-nexus
    volumes:
      - ${SERVICE_HOME}/dockerconf/nexus-data:/sonatype-work
    environment:
      - CONTEXT_PATH=/
      - APPLICATION_PORT=80
    restart: always
    container_name: nexus
    depends_on:
      - jdk
    user: root
    dns:
      - 172.18.1.110
      - 114.114.114.114
    networks:
      default:
         ipv4_address: 172.18.1.101
  mysql_git:
    image: mysql:5.6
    volumes:
      - ${SERVICE_HOME}/dockerconf/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ${SERVICE_HOME}/dockerconf/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: always
    container_name: mysql_git
    dns:
      - 172.18.1.110
      - 114.114.114.114
    networks:
      default:
         ipv4_address: 172.18.1.103
  redis_git:
    image: docker.io/redis:latest
    container_name: redis_git
    dns:
      - 172.18.1.110
      - 114.114.114.114
    restart: always
    networks:
      default:
        ipv4_address: 172.18.1.104
  gitlab:
    image: sameersbn/gitlab:9.5.2
    depends_on:
      - redis_git
      - mysql_git
    links:
      - redis_git
      - mysql_git
    restart: always
    container_name: gitlab
    environment:
      - GITLAB_HOST=www.git.hd.com
      - SMTP_USER=huidaokeji_yf@163.com
      - SMTP_PASS=yzw415666109
      - SMTP_DOMAIN=163.com
      - SMTP_HOST=smtp.163.com
      - SMTP_PORT=25
      - GITLAB_EMAIL_DISPLAY_NAME=git服务器
      - DB_ADAPTER=mysql2
      - DB_HOST=mysql_git
      - GITLAB_TIMEZONE=Asia/Shanghai
      - DB_NAME=gitlabhq_production
      - DB_USER=root
      - DB_PASS=123456
      - REDIS_HOST=redis_git
      - REDIS_PORT=6379
      - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alpha-numeric-string1
      - GITLAB_SECRETS_SECRET_KEY_BASE=long-and-random-alpha-numeric-string2
      - GITLAB_SECRETS_OTP_KEY_BASE=long-and-random-alpha-numeric-string3
    volumes:
      - ${SERVICE_HOME}/dockerconf/gitlab/data:/home/git/data
      - /etc/localtime:/etc/localtime:ro
    dns:
      - 172.18.1.110
      - 114.114.114.114
    networks:
      default:
        ipv4_address: 172.18.1.105
  zentao:
    build: ./zentao
    image: yangzhenwei/centos7-zentao
    container_name: zentao
    volumes:
      - ${SERVICE_HOME}/dockerconf/zentao:/opt/zbox
    dns:
      - 172.18.1.110
      - 114.114.114.114
    restart : always
    networks:
      default:
        ipv4_address: 172.18.1.106
  wiki:
    build: ./wiki
    image: yangzhenwei/centos7-confluence
    container_name: wiki
    depends_on:
      - mysql_git
    links:
      - mysql_git
    dns:
      - 172.18.1.110
      - 114.114.114.114
    restart: always
    user: root
    volumes:
      - ${SERVICE_HOME}/dockerconf/confluence:/confluence
    networks:
      default:
        ipv4_address: 172.18.1.107
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    user: root
    environment:
      - NGINX_PORT=80
    dns:
      - 172.18.1.110
      - 114.114.114.114
    restart: always
    networks:
      default:
        ipv4_address: 172.18.1.108
    volumes:
      - ./nginx/reverse-proxy.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/zhitongche:/www/huidao/com
    command: /bin/bash -c "nginx -g 'daemon off;'"
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    ports:
     - "1194:1194/udp"
    dns:
      - 172.18.1.110
      - 114.114.114.114
    restart: always
    volumes:
     - ./openvpn:/etc/openvpn
     - /etc/localtime:/etc/localtime:ro
    networks:
       default:
        ipv4_address: 172.18.1.109
  dnsmasq:
    build: ./dnsmasq
    image:  andyshinn/dnsmasq
    container_name: dnsmasq
    cap_add:
      - NET_ADMIN
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    dns:
      - 172.18.1.110
      - 114.114.114.114
    volumes:
      - ./dnsmasq/dnsmasqhosts:/etc/dnsmasqhosts
    restart: always
    networks:
      default:
        ipv4_address: 172.18.1.110
    restart: always
  jenkins_4:
    build: ./jenkins_4
    image:  yangzhenwei/centos7-jenkins:0.4
    container_name: jenkins_4
    user: root
    mem_limit: 8G
    memswap_limit: 9G
    cpu_count: 4
#    cpu_period: 100000
#    cpu_shares: 512
    cpu_quota: 400000
#    cpu_percent: 50
    blkio_config:
      weight: 300
      device_read_bps:
        - path: /dev/sdb
          rate: '12mb'
      device_read_iops:
        - path: /dev/sdb
          rate: 120
      device_write_bps:
        - path: /dev/sdb
          rate: '1024k'
      device_write_iops:
        - path: /dev/sdb
          rate: 30
    environment:
        - JAVA_OPTS=-Xmx4g  -Xms128m   -XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=1g  -Xss256k -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled  -XX:+UseCMSCompactAtFullCollection -XX:LargePageSizeInBytes=128m -XX:+UseFastAccessorMethods -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -Dfile.encoding=UTF-8
    volumes:
      - ${SERVICE_HOME}/dockerconf/jenkins_2:/var/jenkins_home
      - mvn_repository:/root/.m2
    dns:
      - 172.18.1.110
      - 114.114.114.114
    restart: always
    networks:
      default:
        ipv4_address: 172.18.1.111
  mysql_dev:
    image: mysql:5.6
    container_name: mysql_dev
    volumes:
      - ./mysql_dev/my.cnf:/etc/mysql/conf.d/my.cnf
      - ${SERVICE_HOME}/dockerconf/mysql_dev/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: always
    container_name: mysql_dev
    networks:
      default:
         ipv4_address: 172.18.1.112
  redis_dev:
    image: docker.io/redis:latest
    container_name: redis_dev
    restart: always
    command: redis-server --requirepass c07e5d2af989ddf7e8eaefc0bca4924d
    networks:
      default:
        ipv4_address: 172.18.1.113
  zookeeper_dev:
    image: zookeeper
    container_name: zookeeper_dev
    restart: always
    networks:
      default:
        ipv4_address: 172.18.1.114
  nginx_dev:
    image: nginx
    container_name: nginx_dev
    user: root
    environment:
      - NGINX_PORT=80
    dns:
      - 172.18.1.110
      - 114.114.114.114
    restart: always
    networks:
      default:
        ipv4_address: 172.18.1.115
    volumes:
      - ./nginx/dev-reverse-proxy.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/dev-nginx.conf:/etc/nginx/nginx.conf
    command: /bin/bash -c "nginx -g 'daemon off;'"
#  registry:
#    image: registry:2
#    container_name: registry
#    dns:
#      - 172.18.1.110
#      - 114.114.114.114
#    restart: always
#    volumes:
#      - ${SERVICE_HOME}/dockerconf/registry2:/var/lib/registry
#      - ./registry/auth:/auth
#      - ./registry/certs:/certs
#    environment:
#      - REGISTRY_AUTH=htpasswd
#      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
#      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
#      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry.crt
#      - REGISTRY_HTTP_TLS_KEY=/certs/registry.key
#    networks:
#      default:
#        ipv4_address: 172.18.1.116
  dubbo-admin:
    image: yangzhenwei/centos7-maven
    container_name: dubbo-admin
    working_dir: /opt/dubbo/dubbo-admin
    dns:
      - 172.18.1.110
      - 114.114.114.114
    depends_on:
      - zookeeper_dev
    links:
      - zookeeper_dev
    volumes:
      - mvn_repository:/root/.m2
      - ${SERVICE_HOME}/dockerconf/dubbo:/opt/dubbo/
    command: mvn jetty:run -Ddubbo.registry.address=zookeeper://zookeeper_dev:2181 -Djetty.port=80
    restart: always
    networks:
      default:
        ipv4_address: 172.18.1.118
  dev:
    image: yangzhenwei/centos7-jdk
    container_name: dev
    user: root
    mem_limit: 5G
    environment:
      - LANG=C.UTF-8
    dns:
      - 172.18.1.110
      - 114.114.114.114
    volumes:
      - mvn_repository:/root/.m2
    restart: always
    networks:
      default:
        ipv4_address: 172.18.1.119
  dubbo-admin-test1:
    image: yangzhenwei/centos7-maven
    container_name: dubbo-admin-test1
    working_dir: /opt/dubbo/dubbo-admin
    dns:
      - 172.18.1.110
      - 114.114.114.114
    volumes:
      - mvn_repository:/root/.m2
      - ${SERVICE_HOME}/dockerconf/dubbo:/opt/dubbo/
    command: mvn jetty:run -Ddubbo.registry.address=zookeeper://www.test1.hd.com:2181 -Djetty.port=80
    restart: always
    networks:
      default:
        ipv4_address: 172.18.1.120
  dubbo-admin-test2:
    image: yangzhenwei/centos7-maven
    container_name: dubbo-admin-test2
    working_dir: /opt/dubbo/dubbo-admin
    dns:
      - 172.18.1.110
      - 114.114.114.114
    volumes:
      - mvn_repository:/root/.m2
      - ${SERVICE_HOME}/dockerconf/dubbo:/opt/dubbo/
    command: mvn jetty:run -Ddubbo.registry.address=zookeeper://www.test2.hd.com:2181 -Djetty.port=80
    restart: always
    networks:
      default:
        ipv4_address: 172.18.1.121
  mysql_yzw:
    image: mysql:5.6
    container_name: mysql_yzw
    volumes:
      - ./mysql_dev/my.cnf:/etc/mysql/conf.d/my.cnf
      - ${SERVICE_HOME}/dockerconf/mysql_yzw/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: always
    networks:
      default:
         ipv4_address: 172.18.1.122
  jenkins_node:
    image: yangzhenwei/centos7-maven
    container_name: jenkins_node
    user: root
    mem_limit: 4G
    volumes:
      - ${SERVICE_HOME}/dockerconf/jenkins_node:/root/jenkins
      - mvn_repository:/root/.m2
      - /etc/localtime:/etc/localtime:ro
    command: /usr/bin/supervisord
    dns:
      - 172.18.1.110
      - 114.114.114.114
    restart: always
    networks:
      default:
        ipv4_address: 172.18.1.123
#  nfs_server:
#    build: ./nfs_server
#    image: yangzhenwei/nfs_server
#    container_name: nfs-server
#    privileged: true
#    volumes:
#      - mvn_repository:/exports/mvn_repository
#    command: /exports/mvn_repository
#    dns:
#      - 172.18.1.110
#      - 114.114.114.114
#    restart: always
#    networks:
#      default:
#         ipv4_address: 172.18.1.131
#  jenkins_4:
#    build: ./jenkins_4
#    image:  yangzhenwei/centos7-jenkins:0.4
#    container_name: jenkins_4
#    user: root
#    mem_limit: 8G
#    memswap_limit: 9G
#    cpu_count: 4
##    cpu_period: 100000
##    cpu_shares: 512
#    cpu_quota: 400000
##    cpu_percent: 50
#    blkio_config:
#      weight: 300
#      device_read_bps:
#        - path: /dev/sdb
#          rate: '12mb'
#      device_read_iops:
#        - path: /dev/sdb
#          rate: 120
#      device_write_bps:
#        - path: /dev/sdb
#          rate: '1024k'
#      device_write_iops:
#        - path: /dev/sdb
#          rate: 30
#    environment:
#        - JAVA_OPTS=-Xmx3g  -Xms3g   -XX:MetaspaceSize=256M -XX:MaxMetaspaceSize=512m  -Xss256k -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled  -XX:+UseCMSCompactAtFullCollection -XX:LargePageSizeInBytes=128m -XX:+UseFastAccessorMethods -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -Dfile.encoding=UTF-8
#        - JVM_OPTS=-Xmx3g  -Xms3g   -XX:MetaspaceSize=256M -XX:MaxMetaspaceSize=512m  -Xss256k -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled  -XX:+UseCMSCompactAtFullCollection -XX:LargePageSizeInBytes=128m -XX:+UseFastAccessorMethods -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70  -Dfile.encoding=UTF-8
#    volumes:
#      - ${SERVICE_HOME}/dockerconf/jenkins_5:/var/jenkins_home
#      - mvn_repository:/root/.m2
#    dns:
#      - 172.18.1.110
#      - 114.114.114.114
#    restart: always
#    networks:
#      default:
#        ipv4_address: 172.18.1.132
#  dev_1:
#    build: ./dev
#    image: centos7:dev_v2
#    container_name: dev_1
#    user: root
#    mem_limit: 5G
#    environment:
#      - LANG=C.UTF-8
#    dns:
#      - 172.18.1.110
#      - 114.114.114.114
#    volumes:
#      - mvn_repository:/root/.m2
#      - /etc/localtime:/etc/localtime:ro
#    restart: always
#    networks:
#      default:
#        ipv4_address: 172.18.1.124
#  dev_2:
#    build: ./dev
#    image: centos7:dev_v2
#    container_name: dev_2
#    user: root
#    mem_limit: 5G
#    environment:
#      - LANG=C.UTF-8
#    dns:
#      - 172.18.1.110
#      - 114.114.114.114
#    volumes:
#      - mvn_repository:/root/.m2
#      - /etc/localtime:/etc/localtime:ro
#    restart: always
#    networks:
#      default:
#        ipv4_address: 172.18.1.125
#  zookeeper_dev_1:
#    image: zookeeper
#    container_name: zookeeper_dev_1
#    restart: always
#    networks:
#      default:
#        ipv4_address: 172.18.1.126
#  redis_dev_1:
#    image: docker.io/redis:latest
#    container_name: redis_dev_1
#    restart: always
#    command: redis-server --requirepass c07e5d2af989ddf7e8eaefc0bca4924d
#    networks:
#      default:
#        ipv4_address: 172.18.1.127
#  zookeeper_dev_2:
#    image: zookeeper
#    container_name: zookeeper_dev_2
#    restart: always
#    networks:
#      default:
#        ipv4_address: 172.18.1.128
#  redis_dev_2:
#    image: docker.io/redis:latest
#    container_name: redis_dev_2
#    restart: always
#    command: redis-server --requirepass c07e5d2af989ddf7e8eaefc0bca4924d
#    networks:
#      default:
#        ipv4_address: 172.18.1.129
#  mysql_dev_2:
#    image: mysql:5.6
#    container_name: mysql_dev_2
#    volumes:
#      - ./mysql_dev/my.cnf:/etc/mysql/conf.d/my.cnf
#      - /etc/localtime:/etc/localtime:ro
#    environment:
#      - MYSQL_ROOT_PASSWORD=123456
#    restart: always
#    networks:
#      default:
#         ipv4_address: 172.18.1.130
  registry:
    restart: always
    image: registry:2
    container_name: registry
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.crt
      REGISTRY_HTTP_TLS_KEY: /certs/registry.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_HTTP_ADDR: 0.0.0.0:443
    volumes:
      - ${SERVICE_HOME}/dockerconf/registry:/var/lib/registry
      - ${SERVICE_HOME}/dockerconf/registry/certs:/certs
      - ${SERVICE_HOME}/dockerconf/registry/auth:/auth
    networks:
      default:
        ipv4_address: 172.18.1.132
  frontend:
    restart: always
    image: konradkleine/docker-registry-frontend:v2
    container_name: frontend
    environment:
      ENV_DOCKER_REGISTRY_HOST: www.reg.hd.com
      ENV_DOCKER_REGISTRY_PORT: 443
      ENV_DOCKER_REGISTRY_USE_SSL: 1
    dns:
      - 172.18.1.110
      - 114.114.114.114
    networks:
      default:
        ipv4_address: 172.18.1.133
  jenkins_online:
    image:  yangzhenwei/centos7-jenkins:0.4
    container_name: jenkins_online
    user: root
    mem_limit: 4G
    memswap_limit: 5G
    cpu_count: 4
#    cpu_period: 100000
#    cpu_shares: 512
    cpu_quota: 400000
#    cpu_percent: 50
    blkio_config:
      weight: 300
      device_read_bps:
        - path: /dev/sdb
          rate: '12mb'
      device_read_iops:
        - path: /dev/sdb
          rate: 120
      device_write_bps:
        - path: /dev/sdb
          rate: '1024k'
      device_write_iops:
        - path: /dev/sdb
          rate: 30
    environment:
        -  >
            JAVA_OPTS=-Xmx3g  -Xms128m  -XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=1g
            -Xss256k -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled
            -XX:+UseCMSCompactAtFullCollection -XX:LargePageSizeInBytes=128m -XX:+UseFastAccessorMethods
            -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70
            -Dsun.jnu.encoding=UTF-8 -Dfile.encoding=UTF-8
    volumes:
      - ${SERVICE_HOME}/dockerconf/jenkins_online:/var/jenkins_home
      - mvn_repository:/root/.m2
    dns:
      - 172.18.1.110
      - 114.114.114.114
    restart: always
    networks:
      default:
        ipv4_address: 172.18.1.134
  ldap:
    image: osixia/openldap:1.1.8
    container_name: ldap
    environment:
      - LDAP_ORGANISATION=huidaokeji
      - LDAP_DOMAIN=huidaokeji.com
      - LDAP_ADMIN_PASSWORD=admin123
    dns:
      - 172.18.1.110
      - 114.114.114.114
    restart: always
    networks:
      default:
        ipv4_address: 172.18.1.135
  phpldapadmin:
    image: osixia/phpldapadmin:0.7.0
    container_name: phpldapadmin
    depends_on:
      - ldap
    links:
      - ldap:ldap-host
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap-host
      - PHPLDAPADMIN_HTTPS=false
    dns:
      - 172.18.1.110
      - 114.114.114.114
    restart: always
    networks:
      default:
        ipv4_address: 172.18.1.136
  ldap-ssp:
    image: grams/ltb-self-service-password
    container_name: ldap-ssp
    depends_on:
      - ldap
    links:
      - ldap:ldap-host
    volumes:
      - ./ldap/config.inc.php:/usr/share/self-service-password/conf/config.inc.php
    dns:
      - 172.18.1.110
      - 114.114.114.114
    restart: always
    networks:
      default:
        ipv4_address: 172.18.1.137
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.1.0/16
volumes:
  mvn_repository:
    external: true

